logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
server:
  error:
    include-message: always
  port: 8091
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ""
    platform: h2
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false
    show-sql: true
eureka:
	client:
		serviceUrl:
			defaultZone: http://localhost:8099/eureka/