logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
server:
  error:
    include-message: always
  port: 8093
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    platform: h2
    url: jdbc:h2:mem:invoiceDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

resilience4j.retry:
  configs:
    default:
      registerHealthIndicator: true
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
  instances:
    customer-service:
      baseConfig: default
      ignoreExceptions:
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: "*"
management.health.retries.enabled: true