spring:
    config:
        import: optional:configserver:http://localhost:8081
    application:
        name: shopping-service
    cloud:
        config:
            username: root
            password: s3cr3t